# Generated by Django 3.1.3 on 2020-11-30 15:18

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201116_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to=post.models.images_directory_path),
        ),
    ]
