# Generated by Django 3.1.3 on 2020-11-16 13:59

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=user.models.user_directory_path),
        ),
    ]
