# Generated by Django 3.1.3 on 2021-02-09 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210201_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, upload_to=user.models.images_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to=settings.AUTH_USER_MODEL)),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_send', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messenger',
            },
        ),
    ]
