# Generated by Django 3.1.3 on 2021-02-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_messengermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messengermodel',
            old_name='receiver_id',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='messengermodel',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
