# Generated by Django 3.1.3 on 2021-02-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_friendrequest_sender_name'),
        ('user', '0007_messengermodel_sender_name'),
    ]

    operations = [
    ]
