# Generated by Django 3.1.3 on 2021-02-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_merge_20210211_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='sender_name',
        ),
    ]
