# Generated by Django 3.1.3 on 2021-02-12 15:19

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_friendrequest_sender_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messengermodel',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=user.models.images_directory_path),
        ),
    ]
