# Generated by Django 3.1.3 on 2021-02-17 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210212_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='photo',
            new_name='image',
        ),
    ]
