# Generated by Django 3.1.3 on 2021-02-17 10:13

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210217_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messengermodel',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=user.models.images_directory_path),
        ),
    ]
