# Generated by Django 3.1.3 on 2021-02-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_commentmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='username',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
